### ISSUE TITLE
Unclear README

### ISSUE THREAD

**Issue by egarrulo** [leoliu/ggtags#106]
I am using Ggtags  0.8.10.

The README is not clear in regard to whether GNU Global should be run with Ctags or Pygments. According to the documentation of GNU Global 6.5, to use Pygments you should set `GTAGSLABEL=pygments` before running `gtags`, but the README does not mention this.  On the contrary, it seems that Ggtas sets "GTAGSLABEL=ctags", and `ggtags-process-environment` is `nil` by default.

Also, how would you use an external `gtags.conf`?  By setting `GTAGSCONF` via `ggtags-process-environment`?

Thanks for your assistance.

**Comment by egarrulo** [comment]
Maybe this package was written for an older version of GNU Global, and now the setup has changed?

**Comment by leoliu** [comment]
Use `ggtags-process-environment` if you want to customise `global` for a project via its environment variables. `ggtags` has the feature of using `gtags.conf` found at the project root. The feature has since been adopted upstream (requiring global 6.2.13+).

Customisation via environment variables is awkward, So these days I often just copy `~/.globalrc` to project root and change it there. We cannot handle pygments like ctags so to use pygments one has to either change gtags.conf or setting the envvar GTAGSLABEL.

**Comment by egarrulo** [comment]
Therefore, does Ggtas need Pygments to work?  Or is it just better than using Ctags?  Thanks for your assistance.

**Comment by leoliu** [comment]
hi @egarrulo,

Global has built-in parsers (tokenisers) for 4-5 languages. Other languages are supported by plugins. `ctags` adds a lot of languages support but cannot parse references. This is where `pygments` comes in. But as it is written in python it can be terribly slow.

HTH,
Leo

**Comment by egarrulo** [comment]
Thanks for your assistance.

**Comment by leoliu** [comment]
See also https://www.gnu.org/software/global for details on each plugin.
