### ISSUE TITLE
Support for multiple GTAGSLABEL or gtags configuration entries

### ISSUE THREAD

**Issue by trashofmasters** [leoliu/ggtags#87]
I'd like to start use multiple gtags configuration entries for different projects. This enables me to skip parsing of specific directories based on the project I'm working on.

I wonder if ggtags can regenerate the tags using a different gtags configuration entry based a some condition, for example the buffer name or mode or its path on the filesystem.

My current `init.el` sets the `GTAGSLABEL` and `GTAGSCONF` environment variables to point to a specific entry in my personal gtags configuration file. This is achieved with the following snippet of elisp:

```lisp
(setenv "GTAGSLABEL" "ctags")
(setenv "GTAGSCONF" "/usr/local/share/gtags/gtags.conf")
```

For example, I often work on project 1 and 2 at the same time. The problem  is that when ggtags runs `gtags` or `global -u` I don't know how to tell it to use one configuration file rather than the other.

```conf
project1:\
	:tc=ctags:tc=htags:\
        :skip=vendor/,docs/,public/libraries/,*.min.js,public/logs/,node_modules/:

project2:\
	:tc=ctags:tc=htags:\
        :skip=vendor/,build/:
```

Can this issue be solved with a per-project local `gtags.conf` file? Would that be honoured by ggtags when regenerating the tags table?

**Comment by leoliu** [comment]
In project1, setenv GTAGSLABEL accordingly and invoke `ggtags-save-project-settings`, which should save you from running setenv again for project1 next time. Do the same for other projects.

Another option is to copy a gtags.conf to your project root and edit it. Since global `6.2.13` it can try finding the config file from the project root before reaching out to `$HOME`. I often use the second option because it also allows me to skip some files or dirs.

**Comment by trashofmasters** [comment]
That was it, thank you for your support.
