### ISSUE TITLE
`M-,' and `M-*' do not work as expected in Emacs 25.0.x

### ISSUE THREAD

**Issue by vvv** [leoliu/ggtags#88]
The documentation says that
```
;; `ggtags' is similar to the standard `etags' package. These keys
;; `M-.', `M-,', `M-*' and `C-M-.' should work as expected in
;; `ggtags-mode'. See the README in https://github.com/leoliu/ggtags
;; for more details.
```

I have a problem with `M-*` and `M-,`.

`M-*` is undefined.

And
```
M-, runs the command xref-pop-marker-stack (found in global-map),
which is an interactive autoloaded compiled Lisp function in
`xref.el'.
```
`xref-pop-marker-stack` pops back to where `M-.` was last invoked.
I don't think this is what `M-,` (`tags-loop-continue`) is supposed to do.

Could you give me any hint on how to debug this issue?

I use Emacs version 25.0.50.1 and this is my [~/.emacs](https://github.com/vvv/dotfiles/blob/master/.emacs).

**Comment by leoliu** [comment]
@vvv,

Thanks for the report. This is due to change in upstream (25.0.x) which unfortunately also change a few standard key bindings that impacted some packages. For example `dired`'s `dired-do-query-replace-regexp` might become harder to use. Since `ggtags.el` needs to be usable in 24.x stable emacsen, it is too soon adapt to 25.0.50. But I'll keep this in mind and update accordingly.

Leo

**Comment by goofansu** [comment]
`M-*` no effect in `24.4`

**Comment by vvv** [comment]
@goofansu: "Works on my machine."™ I have downgraded Emacs to 24.4.90.1 and `M-*` does run `pop-tag-mark` there.

**Comment by goofansu** [comment]
@vvv Hi, I'm using ggtags with erlang-mode. I found `M-*` is `erl-find-source-unwind` in `erlang-mode`, so I remap with `(local-set-key [remap erl-find-source-unwind] 'pop-tag-mark)`

**Comment by leoliu** [comment]
Yes, in that case you have to resolve the conflict yourself. There is really no reason to rebind `M-*` as done by `distel` but it was designed a long while (> 10 years) ago.

**Comment by goofansu** [comment]
@leoliu Ah, yes,  it's conflict with distel. Thanks.

**Comment by kimim** [comment]
The same issue when I upgrade emacs to 25.0, you can define two keys for this:

    (define-key global-map "\M-." 'ggtags-find-tag-dwim)
    (define-key global-map "\M-*" 'pop-tag-mark)

**Comment by vvv** [comment]
Fixed by adding the following lines to `~/.emacs`:
```
(eval-after-load "ggtags"
  '(define-key ggtags-navigation-map "\M-*" 'ggtags-navigation-mode-abort))
```

**Comment by rdotdk** [comment]
Hi @leoliu , thanks for this awesome package, i use it daily :) Since Emacs 25 has been officially released and available for download from the website, is there any plan to make this package work with it? Without rebinding the keys M-. and M-* ? Currently i have the following snippet in my init file for Emacs 25 as mentioned in the above comments

``` elisp

(define-key global-map "\M-." 'ggtags-find-tag-dwim)
(define-key global-map "\M-*" 'pop-tag-mark)

```

Thanks,
Hari

**Comment by rdotdk** [comment]
Thanks :+1:
