### ISSUE TITLE
How to fit ggtags into my workflow

### ISSUE THREAD

**Issue by wrzoski** [leoliu/ggtags#98]
I was using gtags.el  for many years so probably my workflow is highly influenced by it.
I'm used to context stack of the locations visited previously.
On the stack there are infos about:
* location where 'find-tag' has been called
* location within *ggtags-global*
* location of jump made from *ggtags-global*

Going back in locations stack by another binding would lead me back in that history

As ggtags.el seems much better then gtags.el and it's development is really active I'd like to make a switch.

Can you help me configure it to fit my workflow?
Best regards
Lukasz

**Comment by leoliu** [comment]
Hi @wrzoski,

My setup is quite minimal. I have ggtags-mode enabled by default on cc modes and cfengine-mode. I mostly just use keys `M-.` and `M-]`. They either take me directly to the tag (when there is only one match) or pop up an auxiliary window (when there is more than one match) and enable `M-n` and `M-p` keys to move to next or previous match.

Note most commands are placed in the menu bar entry `Ggtags` for easy discovery.

HTH,
Leo

**Comment by wrzoski** [comment]
Hi @leoliu,
Thanks for quick reply.

I've checked your minimal setup and it seems ok. Going back with M-* seems to go back within history. 
What I personally dislike about it is moving around references with M-n, M-p, M-{, M-} opens up many files.
According to my planned workflow M-./M-] would switch to *ggtags-global* automatically, and with help of C-n/C-p/RET I could select interesting match, and the *ggtags-global* would disappear after.
If the selected tag is not the one I was looking for, I would press M-* to reopen up last *ggtags-global* to choose another match, or press M-* one more time to go back to the place where i clicked M-./M-].
I hope it is not too complicated :)

Lucas

**Comment by leoliu** [comment]
hi @wrzoski,

Basically after opening up all these files to get your work done you can kill all buffers visiting current project files by `C-c M-k`.

To do something similar to `gtags.el`, you need to switch to the *ggtags-global* buffer. The buffer is in `ggtags-global-mode`, derived from `compilation-mode`. There are a dozen commands to help you move around. TAB/BACKTAB to move forward/backward on matches, M-}/{ to move across files etc.

If you need a command to quickly pop to *ggtags-global* buffer, something like this will do:

```
(defun ggtags-pop-to-last-buffer ()
  (interactive)
  (pop-to-buffer ggtags-global-last-buffer))
```

Bind it to a key of your choice ;)

I prefer looking at matches in the context of its surrounding lines (with proper font-locking) which at times actually help me decide which match is the one I need. Then I hit `RET` and the auxiliary window goes away so that I can solely focus on the contents. If I need to work on other matches, `M-,` brings back the auxiliary window.

HTH,
Leo
